//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MtpFileTransfer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:/Application/master")]
        public string CopyToDevice_SourceRootDirectoryPath {
            get {
                return ((string)(this["CopyToDevice_SourceRootDirectoryPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Internal storage/Application/master")]
        public string CopyToDevice_DestinationRootDirectoryPath {
            get {
                return ((string)(this["CopyToDevice_DestinationRootDirectoryPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Internal storage/Application/result")]
        public string CopyFromDevice_SourceRootDirectoryPath {
            get {
                return ((string)(this["CopyFromDevice_SourceRootDirectoryPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:/Application/result")]
        public string CopyFromDevice_DestinationRootDirectoryPath {
            get {
                return ((string)(this["CopyFromDevice_DestinationRootDirectoryPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>dir1/file1.txt</string>
  <string>dir1/file2.txt</string>
  <string>dir2/file3.txt</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CopyFromDevice_SourceFileRelativePaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CopyFromDevice_SourceFileRelativePaths"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>dir10/file10.txt</string>
  <string>dir10/file20.txt</string>
  <string>dir20/file30.txt</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CopyToDevice_SourceFileRelativePaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CopyToDevice_SourceFileRelativePaths"]));
            }
        }
    }
}
